### ISSUE TITLE
Build fails on Dokku 0.7.2

### ISSUE THREAD

**Issue by creatingwake** [polettix/sample-mojo#1]
Hi, I've just tried to build this example and I'm getting the following errors right at the end of the build process:
-----> Waiting for 10 seconds ...
1e28269fcc9ad04cbec86d35837b4d6bf6ddfde802180f2805bb5c0aed87160e
remote: App container failed to start!!
=====> perlman web container output:
       setuidgid: fatal: unable to run ./app.pl: access denied
       setuidgid: fatal: unable to run ./app.pl: access denied
       setuidgid: fatal: unable to run ./app.pl: access denied
       setuidgid: fatal: unable to run ./app.pl: access denied
       setuidgid: fatal: unable to run ./app.pl: access denied
       setuidgid: fatal: unable to run ./app.pl: access denied
       setuidgid: fatal: unable to run ./app.pl: access denied
=====> end perlman web container output
To dokku@ZZ.ZZ.ZZ.ZZ:perlman
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@ZZ.ZZ.ZZ.ZZ:perlman'

Running on ubuntu 14.04 LTS  Dokku 0.7.2

**Comment by creatingwake** [comment]
resolved.


chmod +x on app.pl required before git push

**Comment by polettix** [comment]
Hi! Thanks for trying this out and giving feedback.

The execution bit for `app.pl` should be turned on by default. Do you know why it wasn't like this in your clone? Anything I can do/suggest to avoid this problem for others?

Thanks!

**Comment by creatingwake** [comment]
Hi, thanks for taking the time to put up a mojo sample tutorial!

The reason I had issues was that I followed the instructions in your blog post and constructed the project from scratch myself, rather than taking the easy path and cloning the repo.  The blog didn't mention about making the perl script executable - not something I'm used to doing having worked with Python buildpacks in the past.

**Comment by polettix** [comment]
Thanks to you for following up, I'll update the blog post now that you point this out.

This particular issue actually relies on the use of a `Procfile` where you set the command to be run, like this:

    web: ./app.pl daemon --listen "http://*:$PORT"

Hence, you would hit the same problem independently of the language. I'll call `perl` explicitly instead:

    web: perl ./app.pl daemon --listen "http://*:$PORT"

This should only require that `app.pl` is readable, not executable.

**Comment by polettix** [comment]
[eec77a16](https://github.com/polettix/sample-mojo/commit/eec77a161e77dbbca56202fa29c5927a22b0c50b) solves the problem by invoking `perl` explicitly (mirroring the change in the blog post).

**Comment by creatingwake** [comment]
Exactly - I don't see the problem with python projects as my typical dokku/heroku Procfile calls python directly without relying on the shebang
